---
# This Playbook uses three different roles to
# 1) setup Nexus switches
# 2) Setup UCS admin, equiment and LAN related tasks
# After executing this playbook, LAN connectivity should be configured
#
- name: Configure Pure Storage Environment
  hosts: localhost
  collections:
  - purestorage.flasharray
  gather_facts: yes
  roles:
    ### Configure Nexus Switching
    #
    - PUREconfig
    #

