---
# Variables for Equipment related configurations of UCSM
#
# chassis_links options: 1-link, 2-link, 4-link, 8-link, platform-max
# chassis_link_aggr options: port-channel , none (check UCSM version)
# Set to the minimum number of links to a chassis with a minumum of 2-link
#
chassis_links: 4-link
chassis_link_aggr: port-channel
#
# This is the list of all the server ports where chassis and rack servers are connected (enable the ports for rack serverrs as needed)
#
server_port_list:
# UCS Chassis Connections
  - fabric_id: "A"
    slot_id: '1'
    port_id: '25'
  - fabric_id: "A"
    slot_id: '1'
    port_id: '26'
  - fabric_id: "A"
    slot_id: '1'
    port_id: '27'
  - fabric_id: "A"
    slot_id: '1'
    port_id: '28'
  - fabric_id: "B"
    slot_id: '1'
    port_id: '25'
  - fabric_id: "B"
    slot_id: '1'
    port_id: '26'
  - fabric_id: "B"
    slot_id: '1'
    port_id: '27'
  - fabric_id: "B"
    slot_id: '1'
    port_id: '28'
# Rack Server Connections
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '17'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '18'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '17'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '18'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '19'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '20'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '19'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '20'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '21'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '22'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '21'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '22'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '23'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '24'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '23'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '24'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '31'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '32'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '31'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '32'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '33'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '34'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '33'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '34'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '35'
#  - fabric_id: "A"
#    slot_id: '1'
#    port_id: '36'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '35'
#  - fabric_id: "B"
#    slot_id: '1'
#    port_id: '36'
#
# This is the list for Port-Channel Configuration Parameters including uplink ports
# admin_speed can be hard coded to "100gbps" (default to match Nexus Config) or "auto".
#
port_channel_list:
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '33'
    admin_speed: "auto"
    description: "N9K-A:Eth1/1"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '34'
    admin_speed: "auto"
    description: "N9K-A:Eth1/2"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '35'
    admin_speed: "auto"
    description: "N9K-A:Eth1/3"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '36'
    admin_speed: "auto"
    description: "N9K-A:Eth1/4"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '37'
    admin_speed: "auto"
    description: "N9K-B:Eth1/1"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '38'
    admin_speed: "auto"
    description: "N9K-B:Eth1/2"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '39'
    admin_speed: "auto"
    description: "N9K-B:Eth1/3"
  - name: "Po145-Nexus"
    pc_id: '145'
    fabric_id: "A"
    slot_id: '1'
    port_id: '40'
    admin_speed: "auto"
    description: "N9K-B:Eth1/4"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '33'
    admin_speed: "auto"
    description: "N9K-A:Eth1/5"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '34'
    admin_speed: "auto"
    description: "N9K-A:Eth1/6"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '35'
    admin_speed: "auto"
    description: "N9K-A:Eth1/7"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '36'
    admin_speed: "auto"
    description: "N9K-A:Eth1/8"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '37'
    admin_speed: "auto"
    description: "N9K-B:Eth1/5"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '38'
    admin_speed: "auto"
    description: "N9K-B:Eth1/6"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '39'
    admin_speed: "auto"
    description: "N9K-B:Eth1/7"
  - name: "Po146-Nexus"
    pc_id: '146'
    fabric_id: "B"
    slot_id: '1'
    port_id: '40'
    admin_speed: "auto"
    description: "N9K-B:Eth1/8"
