---
vpc_source: 10.1.164.61
vpc_destination: 10.1.164.62
vpc_role_priority: "10"
Baremetal_ntp_dist_IP: '10.1.164.254/24'
# Interface Lists; more interfaces can be added for additional BW
#
mgmt_interface_list:
  - interface: "Ethernet1/9"
    description: "Uplink-SW"

peerlink_interface_list:
  - interface:  "Ethernet1/53"
    description: "N9K-B:Eth1/53"
  - interface:  "Ethernet1/54"
    description: "N9K-B:Eth1/54"
#
FI_A_interface_list:
  - interface:  "Ethernet1/1"
    description: "FI-A:Eth1/33"
  - interface:  "Ethernet1/2"
    description: "FI-A:Eth1/34"
  - interface:  "Ethernet1/3"
    description: "FI-A:Eth1/35"
  - interface:  "Ethernet1/4"
    description: "FI-A:Eth1/36"

#
FI_B_interface_list:
  - interface:  "Ethernet1/5"
    description: "FI-B:Eth1/33"
  - interface:  "Ethernet1/6"
    description: "FI-B:Eth1/34"
  - interface:  "Ethernet1/7"
    description: "FI-B:Eth1/35"
  - interface:  "Ethernet1/8"
    description: "FI-B:Eth1/36"

#
storage_interface_list:
  - interface:  "Ethernet1/37"
    description: "ct0.eth4"
  - interface:  "Ethernet1/38"
    description: "ct1.eth4"

iscsi_vlan: "901"
#
all_interfaces: "{{ mgmt_interface_list + peerlink_interface_list + FI_A_interface_list + FI_B_interface_list + storage_interface_list }}"
